version: "3"

services: 
    web:
        build: ./
        ports: 
            - 8000:8000
        volumes: 
            - ./backend:/backend
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        env_file: 
            - ./social_team/social_team/env.dev
        depends_on: 
            - db
    db:
       image: postgres
       restart: always
       environment:
        POSTGRES_PASSWORD: LocalPassword
        expose: 5432