# Generated by Django 3.0.5 on 2020-04-15 19:05

import cropperjs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_skill', models.CharField(blank=True, choices=[('ANDROID_DEVELOPER', 'Android Developer'), ('DESIGNER', 'Designer'), ('IOS_DEVELOPER', 'IOS Developer'), ('JAVA_DEVELOPER', 'Java Developer'), ('PHP_DEVELOPER', 'PHP Developer'), ('PYTHON_DEVELOPER', 'Python Developer'), ('RAILS_DEVELOPER', 'Rails Developer'), ('WORDPRESS_DEVELOPER', 'Wordpress Developer'), ('OTHER', 'Other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OtherSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_skill', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('avatar', cropperjs.models.CropperImageField(default='avatars/sample.png', upload_to='avatars/')),
                ('bio', markdownx.models.MarkdownxField(default='')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('main_skills', models.ManyToManyField(related_name='mainskill', to='profiles.MainSkill')),
                ('other_skills', models.ManyToManyField(related_name='otherskill', to='profiles.OtherSkill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
