# Generated by Django 3.0.5 on 2020-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='adam_adamkielar.pl', unique=True),
            preserve_default=False,
        ),
    ]
