# Generated by Django 3.0.5 on 2020-04-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
