# Generated by Django 3.0.5 on 2020-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mainskills',
            new_name='main_skills',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='otherskills',
            new_name='other_skills',
        ),
    ]
