# Generated by Django 3.0.5 on 2020-05-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otherskill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
