# Generated by Django 3.0.5 on 2020-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200505_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskill',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_name',
            field=models.CharField(blank=True, default='ewtqt', max_length=255),
            preserve_default=False,
        ),
    ]
