# Generated by Django 3.0.5 on 2020-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200419_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
