# Generated by Django 3.0.5 on 2020-05-04 19:54

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='timeline',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant_requirements',
            field=markdownx.models.MarkdownxField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_timeline',
            field=markdownx.models.MarkdownxField(blank=True, max_length=500, null=True),
        ),
    ]
