# Generated by Django 3.0.5 on 2020-04-22 14:30

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200421_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='applicant_requirements',
            field=markdownx.models.MarkdownxField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_timeline',
            field=markdownx.models.MarkdownxField(default='', max_length=500),
        ),
    ]
